# Generated by Django 5.0.1 on 2024-03-27 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.IntegerField()),
                ('nome', models.TextField()),
                ('data_nasc', models.DateField()),
                ('sexo', models.TextField()),
                ('nome_mae', models.TextField()),
                ('naturalidade', models.TextField()),
                ('data', models.DateField()),
                ('image', models.ImageField(upload_to='imagens/')),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('rua', models.TextField()),
                ('bairro', models.TextField()),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.TextField()),
                ('cidade', models.TextField()),
                ('uf', models.TextField()),
                ('matricula', models.TextField()),
                ('periodo', models.TextField()),
                ('curso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotaAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('media', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.TextField(default='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.turma')),
            ],
        ),
    ]
